ktor {
  deployment {
    port = 8080
    shutdownTimeout = 15000
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

app {
  name = ${NAIS_POD_NAME}
  runtime = ${NAIS_CLUSTER_NAME}
}

external {
  texas {
    tokenEndpoint = ${NAIS_TOKEN_ENDPOINT}
  }
  tsmPdlCache {
    url = "http://tsm-pdl-cache"
  }
}

behandlingsdager {
  ids = ${BEHANDLINGSDAGER_IDS}
}


kafka {
  sykmeldingConsumer.longPoll = PT10S
  config {
    "bootstrap.servers" = ${KAFKA_BROKERS}
    "security.protocol" = "SSL"
    "ssl.truststore.location" = ${KAFKA_TRUSTSTORE_PATH}
    "ssl.truststore.password" = ${KAFKA_CREDSTORE_PASSWORD}
    "ssl.truststore.type" = "jks"
    "ssl.keystore.location" = ${KAFKA_KEYSTORE_PATH}
    "ssl.keystore.password" = ${KAFKA_CREDSTORE_PASSWORD}
    "ssl.keystore.type" = "PKCS12"
    "auto.offset.reset" = "latest"
    "enable.auto.commit" = "false"
    "max.poll.records" = "100"
  }
}
