ktor {
  deployment {
    port = 8080
    shutdownTimeout = 15000
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

app {
  name = "local-pod"
  runtime = "local"
}

external {
  tsmPdlCache {
    url = "http://tsm-pdl-cache"
  }
}
behandlingsdager {
  ids = ","
  ids = ${?BEHANDLINGSDAGER_IDS}
}
sykmeldingConsumer {
  longPoll = PT10S
}