ktor {
  deployment {
    port = 8080
    shutdownTimeout = 15000
  }
  application {
    modules = [no.nav.tsm.ApplicationKt.module]
  }
}

app {
  name = "local-pod"
  runtime = "local"
}

external {
  texas {
    tokenEndpoint = "http://localhost:7164"
  }
  tsmPdlCache {
    url = "http://tsm-pdl-cache"
  }
}

kafka {
  sykmeldingConsumer.longPoll = PT10S
  config {
    "bootstrap.servers" = "localhost:9092"
    "bootstrap.servers" = ${?BOOTSTRAP_SERVERS}
    "security.protocol" = "PLAINTEXT"
    "auto.offset.reset" = "earliest"
    "enable.auto.commit" = "false"
    "max.poll.records" = "1"
  }
}