[versions]
kotlin = "2.4.10"
logback = "1.6.1"
logbackEncoder = "9.0"
kafka = "4.3.1"
mockk = "1.14.11"
testcontainers = "2.0.5"
otel = "2.30.0"
kotest-assertions = "6.2.3"
tsm-sykmeldinger-input = "29"
arrow = "2.2.3"
coroutines = "1.11.0"

[libraries]
kafka-client = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }

# Monitoring and observability
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logbackEncoder" }
otel-annotations = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations", version.ref = "otel" }

# Tsm dependencies
tsm-sykmeldinger-input = { module = "no.nav.tsm.sykmelding:input", version.ref = "tsm-sykmeldinger-input" }

# testing
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest-assertions" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "8.9.0" }
detekt = { id = "dev.detekt", version = "2.0.0-alpha.6" }
