[versions]
kotlin = "2.3.21"
logback = "1.5.32"
logbackEncoder = "9.0"
prometheus = "1.16.5"
kafka = "4.3.0"
mockk = "1.14.9"
testcontainers = "2.0.5"
otel = "2.28.1"
kotest-assertions = "6.1.11"
tsm-sykmeldinger-input = "26"
khealth = "3.0.2"
arrow = "2.2.2.1"
coroutines = "1.11.0"

[libraries]
kafka-client = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }

# Monitoring and observability
khealth = { module = "dev.hayden:khealth", version.ref = "khealth" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logbackEncoder" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "prometheus" }
otel-annotations = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations", version.ref = "otel" }

# Tsm dependencies
tsm-sykmeldinger-input = { module = "no.nav.tsm.sykmelding:input", version.ref = "tsm-sykmeldinger-input" }

# testing
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest-assertions" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version = "8.5.1" }
detekt = { id = "dev.detekt", version = "2.0.0-alpha.3" }
gradle-versions = { id = "com.github.ben-manes.versions", version = "0.54.0" }